// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAbBNzAx-PRAb1QCZYFUDs6yoNtY5mT0D4',
    appId: '1:209268780742:web:527de2520f727393df71c7',
    messagingSenderId: '209268780742',
    projectId: 'walletwizard-e4e01',
    authDomain: 'walletwizard-e4e01.firebaseapp.com',
    storageBucket: 'walletwizard-e4e01.firebasestorage.app',
    measurementId: 'G-NYDM9HGGYP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDHUDKgWUREhUNc410Je7QUgzpbwiaP3LI',
    appId: '1:209268780742:android:d67ada2a658dc5e2df71c7',
    messagingSenderId: '209268780742',
    projectId: 'walletwizard-e4e01',
    storageBucket: 'walletwizard-e4e01.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB2XmZ6h-zhaqHPJCCmN-vEbOrz-VAkQdw',
    appId: '1:209268780742:ios:14c4b8000e6bbabadf71c7',
    messagingSenderId: '209268780742',
    projectId: 'walletwizard-e4e01',
    storageBucket: 'walletwizard-e4e01.firebasestorage.app',
    iosBundleId: 'com.example.walletwizard',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB2XmZ6h-zhaqHPJCCmN-vEbOrz-VAkQdw',
    appId: '1:209268780742:ios:14c4b8000e6bbabadf71c7',
    messagingSenderId: '209268780742',
    projectId: 'walletwizard-e4e01',
    storageBucket: 'walletwizard-e4e01.firebasestorage.app',
    iosBundleId: 'com.example.walletwizard',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAbBNzAx-PRAb1QCZYFUDs6yoNtY5mT0D4',
    appId: '1:209268780742:web:e850344d86a3bf70df71c7',
    messagingSenderId: '209268780742',
    projectId: 'walletwizard-e4e01',
    authDomain: 'walletwizard-e4e01.firebaseapp.com',
    storageBucket: 'walletwizard-e4e01.firebasestorage.app',
    measurementId: 'G-601CBLVN95',
  );
}
